server:
  port: 8082

spring:
  data:
    mongodb:
      database: springTasks
      host: localhost
      port: 27017

logging:
  level:
    org:
      springframework:
        security: DEBUG

#
#security:
#  whitelist: api/v1/auth/**

auth:
  expiration: 604800
  secret: secret_maher_random_8K%#DF&2_java_spring-security
  header: Authorization